# Generated by Django 4.2.17 on 2025-01-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
    ]
