# Generated by Django 4.2.17 on 2025-01-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
