# Generated by Django 4.2.17 on 2025-01-07 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0006_settlement_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='borrower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_settlements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settlement',
            name='settlement_method',
            field=models.CharField(choices=[(1, 'Bank_Transfer'), (2, 'UPI'), (3, 'Cheque'), (4, 'Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lent_settlements', to=settings.AUTH_USER_MODEL),
        ),
    ]
