# Generated by Django 4.2.17 on 2025-01-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_settlement_borrower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='is_deleted',
        ),
    ]
