# Generated by Django 4.2.17 on 2025-01-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_remove_settlement_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.settlement'),
        ),
    ]
