# Generated by Django 4.2.17 on 2025-01-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_expense_settlement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='settlement',
        ),
        migrations.AddField(
            model_name='settlement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
