# Generated by Django 4.2.17 on 2025-01-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('CoreAuth', '0002_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='auth_student_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='auth_student_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
